name: Movies M3U Auto Update

on:
  schedule:
    - cron: '7 */2 * * *'   # avoid 0-minute congestion
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run script
        run: |
          echo "Running at: $(date -u)"
          python provider.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add movies.m3u

          git diff --cached --quiet || git commit -m "Update $(date -u +'%Y-%m-%d %H:%M:%S UTC')"

          git push
